### ISSUE TITLE
能否考虑添加一个用wget下载文件的功能

### ISSUE THREAD

**Issue by LYSSION** [loveyu/LyFM#3]

**Comment by loveyu** [comment]
@LYSSION 
![image](https://user-images.githubusercontent.com/1912373/40600580-8f99a79a-6284-11e8-8ddc-972b9946e73c.png)

这个和你想的差别大么？

**Comment by LYSSION** [comment]
我用的是编译生成的单文件版本，里面没这个功能的。

**Comment by loveyu** [comment]
@LYSSION 可能不会去维护了，那个单文件的维护有点麻烦，如果有需要建议自己尝试调整下。
